version: '3.8'

services:
  mysql_vehicule:
    image: mysql:8.0 # You can specify a different version if needed
    container_name: mysql_vehicule_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Change this to a strong root password
      MYSQL_DATABASE: vehicule_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306" # Exposes MySQL on port 3306 on your host
    volumes:
      - vehicule_db_data:/var/lib/mysql # Persist data for vehicule_DB

  mysql_station:
    image: mysql:8.0 # You can specify a different version if needed
    container_name: mysql_station_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Change this to a strong root password
      MYSQL_DATABASE: station_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306" # Exposes MySQL on port 3307 on your host to avoid port conflict
    volumes:
      - station_db_data:/var/lib/mysql # Persist data for station_DB

  mysql_user:
    image: mysql:8.0 
    container_name: mysql_user_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: user_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306" # Exposes MySQL on port 3308 on your host to avoid port conflict
    volumes:
      - user_db_data:/var/lib/mysql # Persist data for user_DB

volumes:
  vehicule_db_data:
  station_db_data:
  user_db_data: