server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: vehicule-service
          uri: lb://VEHICULE-SERVICE
          predicates:
            - Path=/api/vehicules,/api/vehicules/**
          filters:
            - RewritePath=/api/vehicules(?<segment>.*), /vehicules${segment}
        - id: station-service
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/stations,/api/stations/**
          filters:
            - RewritePath=/api/stations(?<segment>.*), /stations${segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users,/api/users/**
          filters:
            - RewritePath=/api/users(?<segment>.*), /users${segment}
        - id: statistics-service
          uri: lb://STATISTICS-SERVICE
          predicates:
            - Path=/api/statistics,/api/statistics/**
          filters:
            - RewritePath=/api/statistics(?<segment>.*), /api/statistics${segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG