server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    
  # Configuration de sécurité basique
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Configuration du logging
logging:
  level:
    com.example.userservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info 