server:
  port: 8082

spring:
  application:
    name: station-service
  datasource:
    url: jdbc:mysql://localhost:3307/station_DB  # URL MySQL station_DB
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true